default: &default
  adapter: postgresql
  pool: 5
  encoding: utf8

development:
  <<: *default
  database: project_test

production:
  <<: *default
  database: postgres
  username: postgres
  password:
  host: db
