# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9baa32c1c98696b3a1c858b72c2c9eeffc25c496531925a64771eee01e61645a02d32c4882617ec2133f42fb168291c57ccfe82d7f0055157687e858edcbb0f

test:
  secret_key_base: b2644fd0cbc239ed8032a6d03ac4d76987838c8a41201bffcbb3c7e0c7e2a9910e66a4a6cafce18efc43c7cab3b97269a782e8cd962f488ec4b744d319f549fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
